### PR TITLE
Update recipes.xml

### PR DESCRIPTION
**Pull request by Gouki11**

### CODE REVIEW

**Comment by Gouki11** [comment]
Update recipes.xml

**Comment by Gouki11** [comment]
mycommits

**Comment by Gouki11** [comment]
Update recipes.xml

**Review by flipvszero — COMMENTED** [review]
Edited it and found a few bugs within items.xml - take a look - also changed recipes to make harvesting diamonds a tab bit trickier then the 1 to 1 ratio

**Comment by Gouki11** [comment]
Update blocks.xml

**Pull request merged**
